#!/usr/bin/env python3
"""Populate a FABRIC WAN skeleton with synthetic SWARM clusters.

Inputs
------
1. A WAN skeleton produced by ``generate_fabric_wan.py``.
2. A cluster specification describing cluster profiles and facility storage.

Output
------
A fully expanded ``platform_config.json`` for the SimGrid JSON platform loader.

The script is deterministic for a fixed specification and seed. It never modifies
its input skeleton in place.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import random
import re
import sys
from pathlib import Path
from typing import Any, Iterable


class ConfigError(ValueError):
    """Raised when an input JSON document is invalid."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Add synthetic compute clusters, facility storage, links, routes, "
            "and filesystems to a FABRIC WAN skeleton."
        )
    )
    parser.add_argument(
        "--skeleton",
        type=Path,
        required=True,
        help="WAN skeleton generated by generate_fabric_wan.py.",
    )
    parser.add_argument(
        "--spec",
        type=Path,
        required=True,
        help="Cluster specification JSON.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("platform_config.json"),
        help="Expanded platform JSON (default: platform_config.json).",
    )
    parser.add_argument(
        "--manifest-out",
        type=Path,
        help="Optional summary of the sampled platform.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        help="Override the seed stored in the specification.",
    )
    parser.add_argument(
        "--no-head-node",
        action="store_true",
        help=(
            "Do not add one extra host per cluster for the SWARM scheduling head. "
            "By default, output count = compute_nodes + 1."
        ),
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            value = json.load(handle)
    except FileNotFoundError as exc:
        raise ConfigError(f"File not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ConfigError(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(value, dict):
        raise ConfigError(f"Top level of {path} must be a JSON object.")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2)
        handle.write("\n")


def require_object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigError(f"{label} must be a JSON object.")
    return value


def require_nonempty_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{label} must be a non-empty string.")
    return value.strip()


def require_positive_int(value: Any, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ConfigError(f"{label} must be a positive integer.")
    return value


def require_positive_number(value: Any, label: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigError(f"{label} must be a positive number.")
    number = float(value)
    if not math.isfinite(number) or number <= 0:
        raise ConfigError(f"{label} must be a positive finite number.")
    return number


def safe_token(value: str) -> str:
    """Convert a name into a stable SimGrid identifier fragment."""
    token = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip())
    token = re.sub(r"_+", "_", token).strip("_")
    if not token:
        raise ConfigError(f"Cannot construct an identifier from {value!r}.")
    return token


def sample_value(value: Any, rng: random.Random, label: str) -> Any:
    """Sample a scalar or one of the supported distribution objects.

    Supported forms:
      8
      {"min": 8, "max": 64}                         # integer uniform
      {"distribution": "integer_uniform", ...}
      {"distribution": "uniform", "min": 0.1, "max": 1.0}
      {"distribution": "choice", "values": [...]}
      {"distribution": "categorical", "values": [...],
       "probabilities": [...]}
    """
    if not isinstance(value, dict):
        return value

    distribution = value.get("distribution")
    if distribution is None and "min" in value and "max" in value:
        low = value["min"]
        high = value["max"]
        distribution = "integer_uniform" if isinstance(low, int) and isinstance(high, int) else "uniform"

    if distribution in {"integer_uniform", "int_uniform"}:
        low = require_positive_int(value.get("min"), f"{label}.min")
        high = require_positive_int(value.get("max"), f"{label}.max")
        if low > high:
            raise ConfigError(f"{label}.min cannot exceed {label}.max.")
        return rng.randint(low, high)

    if distribution == "uniform":
        low = require_positive_number(value.get("min"), f"{label}.min")
        high = require_positive_number(value.get("max"), f"{label}.max")
        if low > high:
            raise ConfigError(f"{label}.min cannot exceed {label}.max.")
        return rng.uniform(low, high)

    if distribution in {"choice", "categorical"}:
        values = value.get("values")
        if not isinstance(values, list) or not values:
            raise ConfigError(f"{label}.values must be a non-empty array.")
        probabilities = value.get("probabilities")
        if probabilities is None:
            return rng.choice(values)
        if not isinstance(probabilities, list) or len(probabilities) != len(values):
            raise ConfigError(f"{label}.probabilities must match {label}.values.")
        weights = [require_positive_number(p, f"{label}.probabilities") for p in probabilities]
        return rng.choices(values, weights=weights, k=1)[0]

    raise ConfigError(
        f"Unsupported distribution for {label}: {distribution!r}. "
        "Use integer_uniform, uniform, choice, or categorical."
    )


def sample_int(value: Any, rng: random.Random, label: str) -> int:
    return require_positive_int(sample_value(value, rng, label), label)


def sample_string(value: Any, rng: random.Random, label: str) -> str:
    return require_nonempty_string(sample_value(value, rng, label), label)


def choose_profile(
    profiles: list[dict[str, Any]],
    rng: random.Random,
    allowed_names: set[str] | None,
) -> dict[str, Any]:
    candidates = []
    weights = []
    for profile in profiles:
        name = require_nonempty_string(profile.get("name"), "cluster_profiles[].name")
        if allowed_names is not None and name not in allowed_names:
            continue
        weight = profile.get("weight", 1.0)
        candidates.append(profile)
        weights.append(require_positive_number(weight, f"profile {name}.weight"))

    if not candidates:
        allowed = sorted(allowed_names) if allowed_names else []
        raise ConfigError(f"No cluster profile is available for allowed_profiles={allowed}.")
    return rng.choices(candidates, weights=weights, k=1)[0]


def normalize_bool(value: Any, label: str) -> bool:
    if isinstance(value, bool):
        return value
    raise ConfigError(f"{label} must be true or false.")


def capacity_to_size(value: Any, label: str) -> str:
    """Convert a capacity scalar to a loader filesystem size string."""
    if isinstance(value, str):
        return require_nonempty_string(value, label)
    number = require_positive_number(value, label)
    if number.is_integer():
        return f"{int(number)}GB"
    return f"{number}GB"


def storage_capacity_gb(storage: dict[str, Any] | None, rng: random.Random, label: str) -> int:
    if not storage or not storage.get("enabled", False):
        return 0
    raw = storage.get("capacity_gb", 0)
    if raw == 0:
        return 0
    return sample_int(raw, rng, f"{label}.capacity_gb")


def validate_skeleton(platform: dict[str, Any]) -> list[dict[str, Any]]:
    facilities = platform.get("facilities")
    if not isinstance(facilities, list) or not facilities:
        raise ConfigError("WAN skeleton must contain a non-empty facilities array.")

    seen: set[str] = set()
    for index, facility in enumerate(facilities):
        facility_obj = require_object(facility, f"facilities[{index}]")
        name = require_nonempty_string(facility_obj.get("name"), f"facilities[{index}].name")
        if name in seen:
            raise ConfigError(f"Duplicate facility name: {name}")
        seen.add(name)
        for field in ("storage_systems", "clusters", "links", "routes"):
            current = facility_obj.setdefault(field, [])
            if not isinstance(current, list):
                raise ConfigError(f"Facility {name}.{field} must be an array.")

    for field in ("storage_systems", "links", "routes", "filesystems"):
        current = platform.setdefault(field, [])
        if not isinstance(current, list):
            raise ConfigError(f"Top-level {field} must be an array.")
    return facilities


def validate_spec(spec: dict[str, Any]) -> list[dict[str, Any]]:
    profiles = spec.get("cluster_profiles")
    if not isinstance(profiles, list) or not profiles:
        raise ConfigError("cluster_specs.json must contain a non-empty cluster_profiles array.")

    names: set[str] = set()
    for index, profile in enumerate(profiles):
        profile_obj = require_object(profile, f"cluster_profiles[{index}]")
        name = require_nonempty_string(profile_obj.get("name"), f"cluster_profiles[{index}].name")
        if name in names:
            raise ConfigError(f"Duplicate cluster profile name: {name}")
        names.add(name)
        for field in (
            "compute_nodes",
            "cores_per_node",
            "memory_gb_per_node",
            "speed",
            "private_link",
            "loopback",
            "backbone",
        ):
            if field not in profile_obj:
                raise ConfigError(f"Profile {name} is missing required field {field!r}.")
    if "clusters_per_facility" not in spec:
        raise ConfigError("cluster_specs.json is missing clusters_per_facility.")
    return profiles


def make_cluster(
    facility_name: str,
    profile: dict[str, Any],
    ordinal: int,
    rng: random.Random,
    add_head_node: bool,
    facility_storage_capacity_gb: int,
) -> tuple[dict[str, Any], dict[str, Any]]:
    profile_name = require_nonempty_string(profile["name"], "profile.name")
    profile_token = safe_token(profile_name).lower()
    facility_token = safe_token(facility_name)
    cluster_name = f"{facility_token}_{profile_token}_{ordinal}"

    compute_nodes = sample_int(profile["compute_nodes"], rng, f"{profile_name}.compute_nodes")
    total_hosts = compute_nodes + (1 if add_head_node else 0)
    cores = sample_int(profile["cores_per_node"], rng, f"{profile_name}.cores_per_node")
    memory_gb = sample_int(profile["memory_gb_per_node"], rng, f"{profile_name}.memory_gb_per_node")
    speed = sample_string(profile["speed"], rng, f"{profile_name}.speed")

    private = require_object(profile["private_link"], f"{profile_name}.private_link")
    loopback = require_object(profile["loopback"], f"{profile_name}.loopback")
    backbone = require_object(profile["backbone"], f"{profile_name}.backbone")

    private_link = {
        "bandwidth": sample_string(private.get("bandwidth"), rng, f"{profile_name}.private_link.bandwidth"),
        "latency": sample_string(private.get("latency", "0s"), rng, f"{profile_name}.private_link.latency"),
    }
    if "sharing_policy" in private:
        private_link["sharing_policy"] = sample_string(
            private["sharing_policy"], rng, f"{profile_name}.private_link.sharing_policy"
        )

    loopback_cfg = {
        "bandwidth": sample_string(loopback.get("bandwidth"), rng, f"{profile_name}.loopback.bandwidth"),
        "latency": sample_string(loopback.get("latency", "0s"), rng, f"{profile_name}.loopback.latency"),
    }

    local_storage = profile.get("local_storage")
    local_capacity_gb = 0
    node_cfg: dict[str, Any] = {
        "speed": speed,
        "cores": cores,
        "private_link": private_link,
        "loopback": loopback_cfg,
    }

    if local_storage is not None:
        local_storage = require_object(local_storage, f"{profile_name}.local_storage")
        enabled = normalize_bool(local_storage.get("enabled", False), f"{profile_name}.local_storage.enabled")
        if enabled:
            probability = float(local_storage.get("probability", 1.0))
            if not 0.0 <= probability <= 1.0:
                raise ConfigError(f"{profile_name}.local_storage.probability must be between 0 and 1.")
            if rng.random() <= probability:
                local_capacity_gb = storage_capacity_gb(local_storage, rng, f"{profile_name}.local_storage")
                node_cfg["storage"] = {
                    "name": safe_token(str(local_storage.get("name", "local_nvme"))),
                    "read_bandwidth": sample_string(
                        local_storage.get("read_bandwidth"),
                        rng,
                        f"{profile_name}.local_storage.read_bandwidth",
                    ),
                    "write_bandwidth": sample_string(
                        local_storage.get("write_bandwidth"),
                        rng,
                        f"{profile_name}.local_storage.write_bandwidth",
                    ),
                }

    system_type = require_nonempty_string(profile.get("system_type", "HPC"), f"{profile_name}.system_type").upper()
    if system_type not in {"HPC", "AI", "HYBRID", "STORAGE"}:
        raise ConfigError(f"{profile_name}.system_type must be HPC, AI, HYBRID, or STORAGE.")
    has_gpu = normalize_bool(profile.get("has_gpu", False), f"{profile_name}.has_gpu")

    storage_property_gb = local_capacity_gb or facility_storage_capacity_gb
    network_interconnect = str(
        profile.get(
            "network_interconnect",
            backbone.get("bandwidth", private.get("bandwidth", "synthetic")),
        )
    )

    cluster = {
        "name": cluster_name,
        "prefix": f"{cluster_name.lower()}-node-",
        "suffix": "",
        "count": total_hosts,
        "node": node_cfg,
        "backbone": {
            "bandwidth": sample_string(backbone.get("bandwidth"), rng, f"{profile_name}.backbone.bandwidth"),
            "latency": sample_string(backbone.get("latency", "0s"), rng, f"{profile_name}.backbone.latency"),
        },
        # Requires the small generic-properties extension discussed for the loader.
        "properties": {
            "site": facility_name,
            "type": system_type,
            "memory_amount_in_gb": str(memory_gb),
            "storage_amount_in_gb": str(storage_property_gb),
            "has_gpu": "True" if has_gpu else "False",
            "network_interconnect": network_interconnect,
        },
    }

    summary = {
        "facility": facility_name,
        "cluster": cluster_name,
        "profile": profile_name,
        "compute_nodes": compute_nodes,
        "head_nodes": 1 if add_head_node else 0,
        "total_hosts": total_hosts,
        "cores_per_node": cores,
        "memory_gb_per_node": memory_gb,
        "has_gpu": has_gpu,
        "local_storage_gb_per_host": local_capacity_gb,
    }
    return cluster, summary


def add_facility_storage(
    facility: dict[str, Any],
    facility_name: str,
    storage_spec: dict[str, Any] | None,
    rng: random.Random,
    filesystems: list[dict[str, Any]],
) -> tuple[str | None, int]:
    if not storage_spec:
        return None, 0
    enabled = normalize_bool(storage_spec.get("enabled", False), "facility_storage.enabled")
    if not enabled:
        return None, 0

    pfs_name = f"{safe_token(facility_name)}_pfs"
    disk_count = sample_int(storage_spec.get("disk_count", 1), rng, "facility_storage.disk_count")
    capacity_gb = sample_int(storage_spec.get("capacity_gb", 1), rng, "facility_storage.capacity_gb")

    storage = {
        "name": pfs_name,
        "server_speed": sample_string(storage_spec.get("server_speed", "1Gf"), rng, "facility_storage.server_speed"),
        "type": require_nonempty_string(storage_spec.get("type", "JBOD"), "facility_storage.type"),
        "disk_count": disk_count,
        "read_bandwidth": sample_string(
            storage_spec.get("read_bandwidth"), rng, "facility_storage.read_bandwidth"
        ),
        "write_bandwidth": sample_string(
            storage_spec.get("write_bandwidth"), rng, "facility_storage.write_bandwidth"
        ),
    }
    facility["storage_systems"].append(storage)

    mount_point = str(storage_spec.get("mount_point", f"/{pfs_name}/"))
    if not mount_point.startswith("/"):
        raise ConfigError("facility_storage.mount_point must be an absolute path.")
    filesystems.append(
        {
            "name": f"{pfs_name}_fs",
            "storage_system": pfs_name,
            "mount_point": mount_point,
            "size": capacity_to_size(capacity_gb, "facility_storage.capacity_gb"),
        }
    )
    return pfs_name, capacity_gb


def add_local_filesystem(
    cluster: dict[str, Any],
    filesystems: list[dict[str, Any]],
    summary: dict[str, Any],
) -> None:
    if "storage" not in cluster["node"]:
        return
    capacity_gb = summary["local_storage_gb_per_host"]
    if capacity_gb <= 0:
        return
    cluster_name = cluster["name"]
    filesystems.append(
        {
            "name": f"{cluster_name}_local_fs",
            "cluster": cluster_name,
            "mount_point": "/{hostname}/scratch/",
            "size": capacity_to_size(capacity_gb, f"{cluster_name}.local_storage"),
        }
    )


def populate_platform(
    skeleton: dict[str, Any],
    spec: dict[str, Any],
    seed_override: int | None,
    add_head_node: bool,
) -> tuple[dict[str, Any], dict[str, Any]]:
    platform = copy.deepcopy(skeleton)
    facilities = validate_skeleton(platform)
    profiles = validate_spec(spec)

    seed = seed_override if seed_override is not None else int(spec.get("seed", 0))
    rng = random.Random(seed)
    facility_overrides = spec.get("facility_overrides", {})
    if not isinstance(facility_overrides, dict):
        raise ConfigError("facility_overrides must be an object keyed by facility name.")

    storage_spec = spec.get("facility_storage")
    if storage_spec is not None:
        storage_spec = require_object(storage_spec, "facility_storage")

    network_spec = require_object(
        spec.get("intra_facility_network", {"bandwidth": "400Gbps", "latency": "5us"}),
        "intra_facility_network",
    )

    summaries: list[dict[str, Any]] = []
    for facility in facilities:
        facility_name = facility["name"]
        if facility["clusters"] or facility["storage_systems"] or facility["links"] or facility["routes"]:
            raise ConfigError(
                f"Facility {facility_name} is not empty. Use the original WAN skeleton as input "
                "instead of a previously populated platform."
            )

        override = facility_overrides.get(facility_name, {})
        override = require_object(override, f"facility_overrides.{facility_name}")

        cluster_count_spec = override.get("clusters_per_facility", spec["clusters_per_facility"])
        cluster_count = sample_int(cluster_count_spec, rng, f"{facility_name}.clusters_per_facility")

        allowed_names = override.get("allowed_profiles")
        allowed_set: set[str] | None = None
        if allowed_names is not None:
            if not isinstance(allowed_names, list) or not allowed_names:
                raise ConfigError(f"facility_overrides.{facility_name}.allowed_profiles must be a non-empty array.")
            allowed_set = {require_nonempty_string(x, f"{facility_name}.allowed_profiles") for x in allowed_names}

        pfs_name, pfs_capacity_gb = add_facility_storage(
            facility, facility_name, storage_spec, rng, platform["filesystems"]
        )

        # One shared internal link intentionally models contention between all local systems.
        core_link_name = f"{safe_token(facility_name)}_core_link"
        facility["links"].append(
            {
                "name": core_link_name,
                "bandwidth": sample_string(
                    network_spec.get("bandwidth"), rng, "intra_facility_network.bandwidth"
                ),
                "latency": sample_string(
                    network_spec.get("latency", "0s"), rng, "intra_facility_network.latency"
                ),
            }
        )

        clusters: list[dict[str, Any]] = []
        profile_ordinals: dict[str, int] = {}
        for _ in range(cluster_count):
            profile = choose_profile(profiles, rng, allowed_set)
            profile_name = str(profile["name"])
            ordinal = profile_ordinals.get(profile_name, 0)
            profile_ordinals[profile_name] = ordinal + 1
            cluster, summary = make_cluster(
                facility_name,
                profile,
                ordinal,
                rng,
                add_head_node,
                pfs_capacity_gb,
            )
            clusters.append(cluster)
            summaries.append(summary)
            add_local_filesystem(cluster, platform["filesystems"], summary)

        facility["clusters"].extend(clusters)

        # The JSON loader creates symmetric routes for facility-level zone routes.
        for left_index, left in enumerate(clusters):
            for right in clusters[left_index + 1 :]:
                facility["routes"].append(
                    {
                        "src": left["name"],
                        "dst": right["name"],
                        "links": [core_link_name],
                    }
                )

        if pfs_name:
            for cluster in clusters:
                facility["routes"].append(
                    {
                        "src": cluster["name"],
                        "dst": pfs_name,
                        "links": [core_link_name],
                    }
                )

    validate_expanded_platform(platform)
    manifest = {
        "seed": seed,
        "source_skeleton": None,
        "facility_count": len(facilities),
        "cluster_count": len(summaries),
        "head_node_added": add_head_node,
        "clusters": summaries,
    }
    return platform, manifest


def unique_names(items: Iterable[dict[str, Any]], field: str, label: str) -> None:
    seen: set[str] = set()
    for item in items:
        name = require_nonempty_string(item.get(field), f"{label}.{field}")
        if name in seen:
            raise ConfigError(f"Duplicate {label} name: {name}")
        seen.add(name)


def validate_expanded_platform(platform: dict[str, Any]) -> None:
    facilities = platform["facilities"]
    facility_names = {facility["name"] for facility in facilities}
    unique_names(facilities, "name", "facility")
    unique_names(platform.get("links", []), "name", "top-level link")

    for route in platform.get("routes", []):
        src = route.get("src")
        dst = route.get("dst")
        if src not in facility_names or dst not in facility_names:
            raise ConfigError(f"Top-level route references unknown facility: {src} -> {dst}")

    all_zone_names: set[str] = set(facility_names)
    all_link_names: set[str] = {link["name"] for link in platform.get("links", [])}
    all_host_prefixes: set[str] = set()

    for facility in facilities:
        name = facility["name"]
        unique_names(facility["clusters"], "name", f"{name} cluster")
        unique_names(facility["storage_systems"], "name", f"{name} storage")
        unique_names(facility["links"], "name", f"{name} link")

        local_zones = {x["name"] for x in facility["clusters"] + facility["storage_systems"]}
        overlap = all_zone_names.intersection(local_zones)
        if overlap:
            raise ConfigError(f"Duplicate zone name(s): {sorted(overlap)}")
        all_zone_names.update(local_zones)

        local_links = {x["name"] for x in facility["links"]}
        overlap_links = all_link_names.intersection(local_links)
        if overlap_links:
            raise ConfigError(f"Duplicate link name(s): {sorted(overlap_links)}")
        all_link_names.update(local_links)

        for cluster in facility["clusters"]:
            prefix = cluster["prefix"]
            if prefix in all_host_prefixes:
                raise ConfigError(f"Duplicate cluster hostname prefix: {prefix}")
            all_host_prefixes.add(prefix)

        for route in facility["routes"]:
            if route.get("src") not in local_zones or route.get("dst") not in local_zones:
                raise ConfigError(
                    f"Facility {name} route references an unknown local zone: "
                    f"{route.get('src')} -> {route.get('dst')}"
                )
            links = route.get("links")
            if not isinstance(links, list) or not links:
                raise ConfigError(f"Facility {name} route must contain at least one link.")
            unknown = [link for link in links if link not in local_links]
            if unknown:
                raise ConfigError(f"Facility {name} route references unknown links: {unknown}")


def main() -> int:
    args = parse_args()
    try:
        skeleton = load_json(args.skeleton)
        spec = load_json(args.spec)
        platform, manifest = populate_platform(
            skeleton,
            spec,
            seed_override=args.seed,
            add_head_node=not args.no_head_node,
        )
        manifest["source_skeleton"] = str(args.skeleton)
        manifest["source_spec"] = str(args.spec)
        manifest["output"] = str(args.output)

        write_json(args.output, platform)
        if args.manifest_out:
            write_json(args.manifest_out, manifest)

        print(f"Wrote platform: {args.output}")
        print(
            f"Facilities: {manifest['facility_count']}; "
            f"clusters: {manifest['cluster_count']}; "
            f"seed: {manifest['seed']}"
        )
        if not args.no_head_node:
            print("Each cluster includes one extra SWARM head/scheduling host.")
        print(
            "Note: cluster 'properties' require the generic properties extension "
            "to SimGrid-JSON-platform-loader."
        )
        return 0
    except (ConfigError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
